-- dwight/integration.lua
-- Connects Dwight's feature ecosystem into the agentic pipeline.
--
-- This module provides the glue between standalone Dwight features
-- (skills, pragmas, libs, features, commit, etc.) and the agentic
-- execution loop (auto.lua / agentic.lua).
--
-- Responsibilities:
--   build_skills_context()  — skills → XML context for agent prompts
--   build_libs_context()    — libs → XML context for agent prompts
--   pragma_sync(feature)    — propagate @feature: pragmas to new files
--   rebuild_features()      — rebuild feature index after file changes

local M = {}

local api = vim.api

--------------------------------------------------------------------
-- Skills context: inject project-local coding conventions
--------------------------------------------------------------------

--- Build XML context block from all project-local skills.
--- Skills are markdown files in .dwight/skills/ that encode
--- coding conventions, API patterns, and project-specific rules.
--- Returns nil if no skills found or project not initialized.
function M.build_skills_context()
  local ok, skills = pcall(require, "dwight.skills")
  if not ok then return nil end

  local skill_list = skills.list()
  if #skill_list == 0 then return nil end

  local parts = {}
  parts[#parts + 1] = "<skills hint=\"Project-local coding guidelines. Follow these conventions.\">"

  local total_chars = 0
  local MAX_CHARS = 8000  -- Cap total skill content

  for _, skill in ipairs(skill_list) do
    if total_chars >= MAX_CHARS then
      parts[#parts + 1] = "  <!-- ... more skills truncated -->"
      break
    end

    local content = skills.read(skill.name)
    if content and content ~= "" then
      -- Trim individual skills to 2K each
      if #content > 2000 then
        content = content:sub(1, 2000) .. "\n... (truncated)"
      end
      parts[#parts + 1] = string.format('  <skill name="%s">', skill.name)
      parts[#parts + 1] = content
      parts[#parts + 1] = "  </skill>"
      total_chars = total_chars + #content
    end
  end

  parts[#parts + 1] = "</skills>"
  return table.concat(parts, "\n")
end

--------------------------------------------------------------------
-- Libs context: inject library documentation
--------------------------------------------------------------------

--- Build XML context block from project-local library docs.
--- Libs are markdown files in .dwight/libs/ that document
--- dependencies and their APIs (generated by :DwightLib).
--- Returns nil if no libs found.
function M.build_libs_context()
  local ok, libs = pcall(require, "dwight.libs")
  if not ok then return nil end

  local lib_list = libs.list()
  if #lib_list == 0 then return nil end

  local parts = {}
  parts[#parts + 1] = "<libraries hint=\"Project dependency documentation. Use these APIs correctly.\">"

  local total_chars = 0
  local MAX_CHARS = 6000

  for _, lib_name in ipairs(lib_list) do
    if total_chars >= MAX_CHARS then
      parts[#parts + 1] = "  <!-- ... more libs truncated -->"
      break
    end

    local content = libs.read(lib_name)
    if content and content ~= "" then
      if #content > 2000 then
        content = content:sub(1, 2000) .. "\n... (truncated)"
      end
      parts[#parts + 1] = string.format('  <lib name="%s">', lib_name)
      parts[#parts + 1] = content
      parts[#parts + 1] = "  </lib>"
      total_chars = total_chars + #content
    end
  end

  parts[#parts + 1] = "</libraries>"
  return table.concat(parts, "\n")
end

--------------------------------------------------------------------
-- Pragma propagation: keep @feature: tags on new files
--------------------------------------------------------------------

--- Detect the feature name from a request/task description.
--- Returns the feature name (string) or nil.
function M.detect_feature_name(text)
  if not text then return nil end
  -- Match "$feature-name" or "@feature:feature-name" patterns
  return text:match("%$([%w_%-%.]+)")
    or text:match("@feature:([%w_%-%.]+)")
    or text:match("feature%s+([%w_%-%.]+)")
end

--- Detect the correct comment prefix for a file based on extension.
local function comment_prefix(filepath)
  local ext = filepath:match("%.([^.]+)$") or ""
  local map = {
    lua = "-- ", py = "# ", rb = "# ", sh = "# ", bash = "# ",
    go = "// ", rs = "// ", js = "// ", ts = "// ", tsx = "// ", jsx = "// ",
    java = "// ", c = "// ", cpp = "// ", h = "// ", hpp = "// ",
    css = "/* ", scss = "/* ", html = "<!-- ",
  }
  return map[ext]
end

--- Check if a file already has a @feature: pragma.
local function has_feature_pragma(filepath)
  local f = io.open(filepath, "r")
  if not f then return false end
  -- Only check first 10 lines (pragmas go at the top)
  for i = 1, 10 do
    local line = f:read("*l")
    if not line then break end
    if line:match("@feature:") then
      f:close()
      return true
    end
  end
  f:close()
  return false
end

--- Add a @feature: pragma to the top of a file.
--- Returns true if the pragma was added, false if skipped.
function M.add_pragma(filepath, feature_name)
  local prefix = comment_prefix(filepath)
  if not prefix then return false end  -- unknown file type

  if has_feature_pragma(filepath) then return false end  -- already tagged

  local f = io.open(filepath, "r")
  if not f then return false end
  local content = f:read("*a")
  f:close()

  -- Build pragma line
  local pragma_line = string.format("%s@feature:%s\n", prefix, feature_name)

  -- For HTML/CSS, need closing comment
  if prefix == "<!-- " then
    pragma_line = string.format("<!-- @feature:%s -->\n", feature_name)
  elseif prefix == "/* " then
    pragma_line = string.format("/* @feature:%s */\n", feature_name)
  end

  -- Write back with pragma prepended
  local out = io.open(filepath, "w")
  if not out then return false end
  out:write(pragma_line .. content)
  out:close()

  return true
end

--- Propagate @feature: pragmas to new files created during a task.
--- Looks at git diff to find new files, checks if they're near existing
--- feature files, and adds the pragma if missing.
---
--- feature_name: string|nil — if known, only propagate this feature.
---                            if nil, detect from directory proximity.
--- Returns { added = { "path1", "path2" }, skipped = N }
function M.pragma_sync(feature_name)
  local result = { added = {}, skipped = 0 }

  -- Get list of new files from git
  local cwd = vim.fn.getcwd()
  local new_files_raw = vim.fn.system("git diff --name-only HEAD~1..HEAD --diff-filter=A 2>/dev/null")
  if not new_files_raw or vim.trim(new_files_raw) == "" then
    return result
  end

  local new_files = vim.split(vim.trim(new_files_raw), "\n", { plain = true })
  if #new_files == 0 then return result end

  -- Build a map of directories → feature names from existing pragmas
  local dir_features = {}
  if not feature_name then
    pcall(function()
      local features = require("dwight.features")
      for _, name in ipairs(features.names()) do
        local feature = features.build_feature(name)
        if feature then
          for _, file in ipairs(feature.files) do
            local dir = file.path:match("^(.+)/[^/]+$")
            if dir then
              dir_features[dir] = name
            end
          end
        end
      end
    end)
  end

  -- Process each new file
  for _, rel_path in ipairs(new_files) do
    local full = cwd .. "/" .. rel_path

    -- Determine which feature this file belongs to
    local target_feature = feature_name
    if not target_feature then
      -- Check if the file is in a directory that belongs to a feature
      local dir = rel_path:match("^(.+)/[^/]+$")
      if dir then
        target_feature = dir_features[dir]
        -- Also check parent dir (for nested modules like skills/paths.lua)
        if not target_feature then
          local parent = dir:match("^(.+)/[^/]+$")
          if parent then target_feature = dir_features[parent] end
        end
      end
    end

    if target_feature then
      local added = M.add_pragma(full, target_feature)
      if added then
        result.added[#result.added + 1] = rel_path
      else
        result.skipped = result.skipped + 1
      end
    else
      result.skipped = result.skipped + 1
    end
  end

  return result
end

--------------------------------------------------------------------
-- Feature index rebuild
--------------------------------------------------------------------

--- Invalidate the feature cache so the next scan picks up new files.
--- Call after file creation/deletion.
function M.rebuild_features()
  pcall(function()
    local features = require("dwight.features")
    -- Features module rescans on each call, so we just need to
    -- notify the developer that the index has changed
    local names = features.names()
    if #names > 0 then
      pcall(function()
        require("dwight.session_log").append(
          string.format("🔄 Feature index rebuilt: %d features (%s)",
            #names, table.concat(names, ", ")))
      end)
    end
  end)
end

--------------------------------------------------------------------
-- Prompt fragments: reusable instruction blocks
--------------------------------------------------------------------

--- Build the pragma instruction block for agent prompts.
--- Explains the @feature: pragma system and when to use it.
function M.pragma_instructions()
  local features_ok, features = pcall(require, "dwight.features")
  if not features_ok then return "" end

  local names = features.names()
  if #names == 0 then return "" end

  return string.format([[
## Feature Pragmas — IMPORTANT
This project uses `@feature:name` pragma comments to track which files belong to which feature.
Active features: %s

RULES:
- When you CREATE a new file that belongs to a feature, add a pragma comment on line 1.
  Format: `// @feature:feature-name Description of what this file does`
  (use the comment style for the file's language: `--` for Lua, `#` for Python, `//` for Go/JS/TS)
- When you SPLIT a file into multiple files, EVERY new file must get the pragma from the original.
  Example: splitting `skills.lua` (@feature:skills) into `skills/paths.lua`, `skills/picker.lua`
  → each new file gets `-- @feature:skills` on line 1.
- When you MOVE a file, the pragma moves with it (it's just a comment in the source).
- Do NOT remove existing pragmas. They are how the project tracks feature boundaries.
- The description after the feature name is optional but helpful.
]], table.concat(names, ", "))
end

--- Build the full integration context for an agent prompt.
--- Combines skills, libs, and pragma instructions.
function M.build_full_context()
  local parts = {}

  local skills_ctx = M.build_skills_context()
  if skills_ctx then parts[#parts + 1] = skills_ctx end

  local libs_ctx = M.build_libs_context()
  if libs_ctx then parts[#parts + 1] = libs_ctx end

  local pragma_inst = M.pragma_instructions()
  if pragma_inst ~= "" then parts[#parts + 1] = pragma_inst end

  if #parts == 0 then return nil end
  return table.concat(parts, "\n\n")
end

--------------------------------------------------------------------
-- Feature-scoped task context
--------------------------------------------------------------------

--- Build detailed context for features referenced in a task description.
--- Unlike build_project_context() which gives a summary of ALL features,
--- this provides full file signatures and source snippets for the
--- specific feature(s) the task is working on.
--- Returns XML string or nil.
function M.build_feature_context(text)
  if not text then return nil end

  local features_ok, features = pcall(require, "dwight.features")
  if not features_ok then return nil end

  -- Find all feature names referenced in the text
  local referenced = {}
  local seen = {}

  -- Match $feature-name patterns
  for name in text:gmatch("%$([%w_%-%.]+)") do
    if not seen[name] then
      seen[name] = true
      referenced[#referenced + 1] = name
    end
  end

  -- Also match "feature X" patterns
  for name in text:gmatch("@feature:([%w_%-%.]+)") do
    if not seen[name] then
      seen[name] = true
      referenced[#referenced + 1] = name
    end
  end

  if #referenced == 0 then return nil end

  local parts = {}
  local total_chars = 0
  local MAX_CHARS = 15000

  for _, name in ipairs(referenced) do
    if total_chars >= MAX_CHARS then break end

    local feature = features.build_feature(name)
    if feature then
      -- Use the full XML format which includes signatures
      local xml = features.format_xml(feature)
      if xml then
        parts[#parts + 1] = xml
        total_chars = total_chars + #xml
      end

      -- Also include source snippets (first 2KB of each file)
      local cwd = vim.fn.getcwd()
      for _, file in ipairs(feature.files) do
        if total_chars >= MAX_CHARS then break end
        local full = file.path:sub(1, 1) == "/" and file.path
          or (cwd .. "/" .. file.path)
        local f = io.open(full, "r")
        if f then
          local content = f:read("*a")
          f:close()
          if content and #content > 0 then
            if #content > 2000 then
              content = content:sub(1, 2000) .. "\n... (truncated)"
            end
            parts[#parts + 1] = string.format(
              '<feature_source path="%s">\n%s\n</feature_source>',
              file.path, content)
            total_chars = total_chars + #content
          end
        end
      end
    end
  end

  if #parts == 0 then return nil end
  return "<feature_context hint=\"Detailed context for features this task modifies. "
    .. "Use exact function signatures and types from here.\">\n"
    .. table.concat(parts, "\n")
    .. "\n</feature_context>"
end

--------------------------------------------------------------------
-- Smart commit messages
--------------------------------------------------------------------

--- Generate a descriptive commit message from the current git diff.
--- Uses diff stat to list changed files grouped by action.
--- Returns a string suitable for `git commit -m`.
function M.smart_commit_message(task_num, total, title)
  local parts = {}

  -- Infer conventional commit type from the task title
  local lower = (title or ""):lower()
  local prefix = "feat"
  if lower:match("fix") or lower:match("bug") or lower:match("repair") or lower:match("patch") then
    prefix = "fix"
  elseif lower:match("refactor") or lower:match("clean") or lower:match("reorganize") or lower:match("restructur") then
    prefix = "refactor"
  elseif lower:match("doc") or lower:match("readme") or lower:match("comment") then
    prefix = "docs"
  elseif lower:match("test") or lower:match("spec") or lower:match("coverage") then
    prefix = "test"
  elseif lower:match("style") or lower:match("format") or lower:match("lint") then
    prefix = "style"
  elseif lower:match("build") or lower:match("ci") or lower:match("deploy") or lower:match("pipeline") then
    prefix = "ci"
  elseif lower:match("chore") or lower:match("config") or lower:match("setup") or lower:match("deps") or lower:match("dependenc") then
    prefix = "chore"
  elseif lower:match("perf") or lower:match("optimi") or lower:match("speed") or lower:match("fast") then
    prefix = "perf"
  end

  -- Build a clean summary from the task title
  local summary = title or "automated change"
  -- Strip leading verbs that duplicate the prefix
  summary = summary
    :gsub("^%s*[Aa]dd%s+", "")
    :gsub("^%s*[Ff]ix%s+", "")
    :gsub("^%s*[Rr]efactor%s+", "")
    :gsub("^%s*[Ii]mplement%s+", "")
    :gsub("^%s*[Uu]pdate%s+", "")
    :gsub("^%s*[Cc]reate%s+", "")
  summary = vim.trim(summary)
  -- Lowercase the first char for conventional commit style
  if #summary > 0 then
    summary = summary:sub(1, 1):lower() .. summary:sub(2)
  end
  -- Truncate to fit 72 char limit
  local max_len = 72 - #prefix - 2
  if #summary > max_len then summary = summary:sub(1, max_len) end

  parts[#parts + 1] = string.format("%s: %s", prefix, summary)

  -- Get changed files grouped by type
  local stat = vim.fn.system("git diff --cached --stat --no-color 2>/dev/null")
  if stat and vim.trim(stat) ~= "" then
    -- Extract summary line (e.g., "5 files changed, 200 insertions(+), 50 deletions(-)")
    local summary = stat:match("(%d+ files? changed[^\n]*)")
    if summary then
      parts[#parts + 1] = ""
      parts[#parts + 1] = summary
    end
  end

  -- Get new vs modified files
  local new_files = vim.fn.system("git diff --cached --name-only --diff-filter=A 2>/dev/null")
  local mod_files = vim.fn.system("git diff --cached --name-only --diff-filter=M 2>/dev/null")
  local del_files = vim.fn.system("git diff --cached --name-only --diff-filter=D 2>/dev/null")

  local function file_list(raw, label)
    if not raw or vim.trim(raw) == "" then return end
    local files = vim.split(vim.trim(raw), "\n", { plain = true })
    if #files > 0 then
      parts[#parts + 1] = ""
      if #files <= 5 then
        parts[#parts + 1] = label .. ": " .. table.concat(files, ", ")
      else
        parts[#parts + 1] = string.format("%s: %s (+%d more)",
          label, table.concat({files[1], files[2], files[3]}, ", "), #files - 3)
      end
    end
  end

  file_list(new_files, "New")
  file_list(mod_files, "Modified")
  file_list(del_files, "Deleted")

  return table.concat(parts, "\n")
end

--------------------------------------------------------------------
-- Post-session analysis
--------------------------------------------------------------------

--- Run post-session analysis after a successful DwightAuto/DwightRefactor.
--- Checks for oversized features, stale docs, and audit suggestions.
--- Outputs directly to the status buffer.
function M.post_session(request, sessions, status)
  -- 1. Check for oversized features that may need splitting
  pcall(function()
    local split = require("dwight.split")
    local oversized = split.audit()
    if #oversized > 0 then
      status.append("")
      status.append("⚠️  Feature size warnings:")
      for _, r in ipairs(oversized) do
        local a = r.analysis
        status.append(string.format("  $%s — %s (%d files, %d lines)",
          r.name, r.reason, a.file_count, a.total_lines))
      end
      status.append("  → Run :DwightSplitFeature to split large features")
    end
  end)

  -- 2. Identify changed features and suggest audit
  local changed_features = {}
  pcall(function()
    -- Collect all files changed across sessions
    local changed_files = {}
    for _, s in ipairs(sessions or {}) do
      for _, f in ipairs(s.files_created or {}) do changed_files[f] = true end
      for _, f in ipairs(s.files_edited or {}) do changed_files[f] = true end
    end

    -- Also check git for changed files
    local diff_files = vim.fn.system("git diff --name-only HEAD~" .. #sessions .. "..HEAD 2>/dev/null")
    if diff_files then
      for f in diff_files:gmatch("[^\n]+") do changed_files[f] = true end
    end

    -- Map changed files to features
    local features = require("dwight.features")
    for _, name in ipairs(features.names()) do
      local feature = features.build_feature(name)
      if feature then
        for _, file in ipairs(feature.files) do
          if changed_files[file.path] then
            changed_features[name] = true
          end
        end
      end
    end
  end)

  local cf_list = {}
  for name in pairs(changed_features) do cf_list[#cf_list + 1] = "$" .. name end
  table.sort(cf_list)

  if #cf_list > 0 then
    status.append("")
    status.append("📋 Suggested follow-ups:")
    status.append(string.format("  Changed features: %s", table.concat(cf_list, ", ")))
    status.append("  → :DwightAudit <feature>  — check code quality")
    status.append("  → :DwightDevDocs          — update developer documentation")
  end

  -- 3. Suggest squash + smart commit
  local commit_count = #sessions
  if commit_count > 1 then
    status.append("")
    status.append(string.format(
      "💡 %d checkpoint commits were made. To clean up git history:",
      commit_count))
    status.append(string.format(
      "  → :DwightSquash           — squash into one commit with a smart message"))
  end

  -- 4. If solving a GitHub issue, offer PR
  pcall(function()
    local gh = require("dwight.github")
    if gh._active_issue then
      status.append("")
      status.append(string.format("🐙 Solving GitHub issue #%d — ready for PR:",
        gh._active_issue.number))
      status.append("  → :DwightPR               — push and create pull request")
    end
  end)
end

--------------------------------------------------------------------
-- Squash: combine dwight checkpoint commits into one
--------------------------------------------------------------------

--- Squash all dwight checkpoint commits since the last non-dwight commit
--- into a single commit with a smart message.
--- If callback is provided, generates an LLM commit message (async).
--- Otherwise uses a combined summary.
function M.squash()
  -- Find how many consecutive dwight commits there are
  local log_raw = vim.fn.system(
    "git log --oneline --format='%s' -50 2>/dev/null")
  if not log_raw or vim.trim(log_raw) == "" then
    vim.notify("[dwight] No git history found.", vim.log.levels.WARN)
    return
  end

  local count = 0
  for line in log_raw:gmatch("[^\n]+") do
    if line:match("^dwight") then
      count = count + 1
    else
      break
    end
  end

  if count <= 1 then
    vim.notify("[dwight] Only 1 dwight commit found — nothing to squash.", vim.log.levels.INFO)
    return
  end

  vim.notify(string.format("[dwight] Squashing %d dwight commits…", count), vim.log.levels.INFO)

  -- Collect the titles from the commits being squashed
  local titles_raw = vim.fn.system(
    string.format("git log --oneline --format='%%s' -%d 2>/dev/null", count))
  local titles = {}
  if titles_raw then
    for line in titles_raw:gmatch("[^\n]+") do
      -- Strip the "dwight(N/M): " or "dwight: " prefix
      local clean = line:gsub("^dwight%([%d/]+%): ", ""):gsub("^dwight: ", "")
      if clean ~= "" then titles[#titles + 1] = clean end
    end
  end

  -- Soft reset to before the dwight commits
  local reset_code = os.execute(
    string.format("cd %s && git reset --soft HEAD~%d 2>/dev/null",
      vim.fn.shellescape(vim.fn.getcwd()), count))
  if reset_code ~= 0 then
    vim.notify("[dwight] Git reset failed — cannot squash.", vim.log.levels.ERROR)
    return
  end

  -- Try to generate a smart message using DwightCommit's LLM flow
  local commit_ok, commit = pcall(require, "dwight.commit")
  if commit_ok and commit.generate then
    -- DwightCommit will see the staged diff and open an editor
    vim.notify(string.format(
      "[dwight] Squashed %d commits. Generating commit message…", count),
      vim.log.levels.INFO)
    commit.generate()
  else
    -- Fallback: commit with combined summary
    local msg = "dwight: " .. table.concat(titles, "; "):sub(1, 200)
    vim.fn.system(string.format(
      "cd %s && git commit -m %s --no-verify 2>/dev/null",
      vim.fn.shellescape(vim.fn.getcwd()),
      vim.fn.shellescape(msg)))
    vim.notify(string.format(
      "[dwight] ✅ Squashed %d commits into one.", count), vim.log.levels.INFO)
  end
end

return M
